theme: jekyll-theme-architect
<h1>Tiye's First Website!</h1>
    <Body>
    Welcome to my introduction to coding! It's been pretty fun so far making this static website and learning more coding skills!
        </Body>
